### PR TITLE
Fix Engine and EventBus to use Laravel Dispatcher without implement EventBusInterface. Resolves #85

### LINKED ISSUE #85: Fix Engine and EventBus to use Laravel Dispatcher without implement EventBusInterface

### PR DESCRIPTION
**Pull request by caleeli**

### CODE REVIEW

File: tests/ProcessMaker/Test/Models/ExecutionInstanceRepository.php [hunk 1]
```diff
@@ -29,7 +29,8 @@ class ExecutionInstanceRepository implements ExecutionInstanceRepositoryInterfac
      */
     public function createExecutionInstance()
     {
-        return new \ProcessMaker\Test\Models\ExecutionInstance();
+        die('Removed!');
+        //return new \ProcessMaker\Test\Models\ExecutionInstance();
```
Comment (danloa) [inline tests/ProcessMaker/Test/Models/ExecutionInstanceRepository.php]: Delete commented code

File: tests/ProcessMaker/Test/Models/ExecutionInstanceRepository.php [hunk 2]
```diff
@@ -29,7 +29,8 @@ class ExecutionInstanceRepository implements ExecutionInstanceRepositoryInterfac
      */
     public function createExecutionInstance()
     {
-        return new \ProcessMaker\Test\Models\ExecutionInstance();
+        die('Removed!');
```
Comment (danloa) [inline tests/ProcessMaker/Test/Models/ExecutionInstanceRepository.php]: is this die needed?
